xserver.c: Don't FTBFS when built with  -Werror=unused-result. (Closes: #638600).
Amends these compiler errors when doing a hardened build:

```
xserver.c: In function 'nodm_xserver_read_window_path':
xserver.c:413:9: error: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Werror=unused-result]
         asprintf(&newwindowpath, "%lu", num);
         ^
xserver.c:415:9: error: ignoring return value of 'asprintf', declared with attribute warn_unused_result [-Werror=unused-result]
         asprintf(&newwindowpath, "%s:%lu", windowpath, num);
         ^
```